---
- name: Deploy example app to my-server.com
  hosts: all
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}"
    ansistrano_deploy_to: "/tmp/my-app.com"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: copy
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }