version: '3'
services:
  ansistrano:
    image: "lavoweb/ansistrano"
    volumes:
      - "./host:/var/host"
      - "./deploy.yml:/var/deploy.yml"
    extra_hosts:
      - "docker.local:192.168.99.100"