FROM lavoweb/php-7.3:magento2
MAINTAINER Aurélien Lavorel <aurelien@lumao.eu>

RUN pecl install xdebug-2.9.8
RUN docker-php-ext-enable xdebug
RUN echo 'xdebug.remote_enable = On' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
     echo 'xdebug.remote_autostart= On' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
     echo 'xdebug.remote_connect_back = On' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN rm -f  /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
