FROM lavoweb/php-8.3:composer
MAINTAINER Aurélien Lavorel <aurelien@lumao.eu>

RUN composer require --ignore-platform-reqs magento/magento-coding-standard
RUN vendor/bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard/,../../phpcompatibility/php-compatibility