FROM lavoweb/php-7.0
MAINTAINER Aurélien Lavorel <aurelien@lavoweb.net>

RUN curl -s https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/
RUN chmod +x composer.phar
RUN ln -s /usr/local/bin/composer.phar /usr/local/bin/composer