FROM lavoweb/php-7.0
MAINTAINER Aurélien Lavorel <aurelien@lavoweb.net>

RUN apt-get --yes --force-yes install unzip
RUN echo "memory_limit=-1" >  /usr/local/etc/php/conf.d/memory.ini
RUN curl -s https://getcomposer.org/installer | php
RUN chmod +x composer.phar
RUN mv composer.phar /usr/local/bin/
RUN ln -s /usr/local/bin/composer.phar /usr/local/bin/composer
RUN composer global require hirak/prestissimo
