FROM ubuntu:22.04

RUN apt-get update && apt-get install -y openssh-server gnupg
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
RUN echo 'root:root' | chpasswd
RUN mkdir /run/sshd

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-o", "ListenAddress=0.0.0.0"]